name: activity workflow
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - main
      - "dev-*" # dev dev-new dev-new-button
      - "feat/**" # feat feat/new feat/new/button

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: test node js version
        run: node --version
      - name: install dependencies
        run: npm ci
      - name: run unit test
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps: 
      - name: checkout
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: build project
        id: publish
        run: npm run build
      - name: publish js filename
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      
      - name: upload dist file
        uses: actions/upload-artifact@v4
        with:
          name: dist-file
          path: |
            ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with: 
          name: dist-file
      - name: check 
        run: ls -al
      - name: show the output from build
        run: echo ${{ needs.build.outputs.script-file }}

